services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    image: node:18
    command: sh -c "sleep 300"