services:
  db:
    container-name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"

  redis:
    container-name: redis
    image: redis
    ports:
      - "6379:6379"

  web:
    container-name: mynode-app
    build .
    depends_on: 
      - db
      - redis
    ports: 
      - "3000:3000"